import { Inter } from "next/font/google";

// import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/custom/navbar/Navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Cursor from "@/components/custom/Cursor";
import StoreProvider from "@/components/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

// const soraFont = localFont({
//   src: '/fonts/Sora-Regular.ttf',
//   display: 'swap',
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sora">
        
      {/* <body className={inter.className}> */}
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <StoreProvider>
            {/* <Cursor /> */}
            <Navbar />
            {children}
            </StoreProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
